### PR TITLE
Adds JSON encoded data format

### PR DESCRIPTION
**Pull request by csabahenk**
Introducing the `-j`, `--json` switch:

```
> gron -j <<<  '{"a":{"b":["c"]}}'  | tee out.jgron          
[[],{}]                 
[["a"],{}]              
[["a","b"],[]]          
[["a","b",0],"c"] 
> cat out.jgron  | gron -j -u                                            
{                       
  "a": {                
    "b": [              
       "c"              
    ]                   
  }                     
}                       
```

### CODE REVIEW

**Comment by tomnomnom** [comment]
Thanks for your PR, @csabahenk!

I think this will take me a little while to review. In the meantime, can you tell me a bit more about the output format and what it's good for? I'm finding it a little difficult to see what it's good for / why I might want it

**Comment by csabahenk** [comment]
I updated the commits to amend some suboptimal allocations.
I'll provide rationale / use case later.

**Comment by tomnomnom** [comment]
Hey! Just to let you know that I'm planning to review this this week. It's a hefty change, but you put forward a very good case for merging it. Thank you!

**Comment by csabahenk** [comment]
Would you like me to resolve the conflict and update the PR?

**Comment by tomnomnom** [comment]
@csabahenk I've finally had a chance to have a look through everything! Yes, if you fix the conflicts I will merge it :) Thank you!

**Comment by csabahenk** [comment]
@tomnomnom all conflicts are reduced to ashes!

**Comment by tomnomnom** [comment]
Merged! Thank you so much for your contribution :)

**Pull request merged**
